spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/oriontek}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.oriontek.clients: DEBUG
    org.hibernate.SQL: DEBUG
